#! /usr/bin/env bash

export DMTSGITDIR="${HOME}/majstaf/d_metsys_git/d_metsys"
export DMTSWORKDIR="${HOME}/majstaf/d_metsys_git/d_metsys_source"

git_dmts="/usr/bin/git --git-dir=${DMTSGITDIR} --work-tree=${DMTSWORKDIR}"

echo "Push-ing to d_GITHUB ..."
echo "---"
${git_dmts} push github_dmetsys master

echo

echo "Push-ing to d_GITLAB ..."
echo "---"
${git_dmts} push gitlab_dmetsys master

