#! /usr/bin/env bash

PTH="${HOME}/majstaf/majrcs/aliases-jbez0rg"

if [ $# -gt 0 ]; then
	cmd='cat ${PTH} | \grep "^alias" | sed -e "/^#/d" -e "/^$/d" | sed "s/^alias //" | grep "$1"'
else
	cmd='cat ${PTH} | \grep "^alias" | sed -e "/^#/d" -e "/^$/d" | sed "s/^alias //"'
fi

while read LINE; do
	alias_name=$(echo $LINE | cut -d'=' -f1)
	alias_value=$(echo $LINE | cut -d'=' -f2-)
	printf "%-15s%s\n" "$alias_name" "$alias_value"
done < <(eval "${cmd}")
