#! /usr/bin/env bash
# gadd_gcmt_jbe
# last change: 20240911

gcmd="/usr/bin/git add --verbose ."
gcmt="${HOME}/.local/bin/gcommit_timestamp_jbe"


# display commands
echo -en "running: ${gcmd}\n" && ${gcmd}
echo
echo -en "running: ${gcmt}\n" && ${gcmt}

