#! /usr/bin/env bash
# ghgltestpush_jbe
# last update: 20240228_jbe

### rmts=( $(git remote) )
### 
### COLOR_SET="\e[1;92m"
### COLOR_RESET="\e[0m"
### 
### 
### 
### for rmt in "${rmts[@]}"
### do
### 		echo "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
### 			git push --dry-run ${rmt} main
### 				echo "---"
### 			done
### 			echo ""
### 
### 
#########################################################################

rmts=( $(git remote) )

COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"

for rmt in "${rmts[@]}"
do
	echo -n "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
	/usr/bin/git push --dry-run ${rmt} main &> status
	grep 'main' status > /dev/null
	if [[ $? -eq 0 ]]; then
		printf " ${COLOR_SET} NEED TO PUSH!!\n"
		cat status
		rm status > /dev/null
		printf "${COLOR_RESET}"
	else
		echo " nothig to push!"
		rm status > /dev/null
	fi
done

