#! /usr/bin/env bash
# ghgltestpush_jbe
# last update: 20240228_jbe

rmts=( $(git remote) )

for rmt in "${rmts[@]}"
do
		echo "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
			git push --dry-run ${rmt} main
				echo "---"
			done
			echo ""
