#! /usr/bin/env bash
# ghgl_push_jbe
# last change: 20240821_jbe

rmts=( $(git remote) )

for rmt in "${rmts[@]}"; do
	echo "[INFO] git testpush in: $(git remote get-url ${rmt}) ..."
	git push ${rmt} main
	echo "---"
done
echo ""

