#! /usr/bin/env bash
# filename: jbegtstst
# last edit: 20240228_jbe

### CURRDIR=$PWD
### cd ~/majstaf/jbegit
### for DDD in $(find * -maxdepth 0 -type d | grep -v 'vlpprs_jbe'); do
### 	echo "[INFO] checking git status in ${DDD} ..."
### 	cd $DDD
### 	/usr/bin/git status
### 	cd ..
### 	echo -e "\n---"
### done
### cd ${CURRDIR}
### 
### 
### JBEVOLGITDIR="${HOME}/majstaf/jbegit/vlpprs_jbe"
### JBEVOLWORKDIR="${HOME}/majstaf/majvolpejpers"
### echo "[INFO] checking git status in ${JBEVOLGITDIR} ..."
### JBEVCMD="/usr/bin/git --git-dir=${JBEVOLGITDIR} --work-tree=${JBEVOLWORKDIR}"
### ${JBEVCMD} status
### echo -e "\n---"
### 
#######################################################################################

COLOR_SET="\e[1;92m"
COLOR_RESET="\e[0m"
CURRDIR=$PWD


function get_status() {
	cmd=$1
	OUTPUT=$(${cmd} status)

	echo $OUTPUT | grep -i "git push\|untracked\|modified" > /dev/null

	if [[ $? -ne 0 ]]; then
		echo -n "[INFO] checking git status in ${DDD} ..."
		echo " nothing to commit"
	else
		printf "${COLOR_SET}"
		echo -n "[INFO] checking git status in ${DDD} ..."
		printf " NEED TO ADD and/or COMMIT!!\n"
		printf "${COLOR_RESET}"
		${cmd} status
	fi
}

cd ~/majstaf/jbegit/
for DDD in $(find * -maxdepth 0 -type d | grep -v 'vlpprs_jbe'); do
	cd $DDD &> /dev/null

	get_status "/usr/bin/git"

	cd ..
	echo "---"
done

# volpejpers
DDD="vlpprs_jbe"
# get_status '/usr/bin/git --git-dir=/home/gregor.redelonghi/majstaf_en/engit/vlpprs_en --work-tree=/c/Users/gregor.redelonghi/majstaf_en/en_staf/majvolpejprs'
JBEVOLGITDIR="${HOME}/majstaf/jbegit/vlpprs_jbe"
JBEVOLWORKTREE="${HOME}/majstaf/majvolpejpers"
get_status="/usr/bin/git --git-dir=${JBEVOLGITDIR} --work-tree=${JBEVOLWORKTREE}"
echo "---"

cd ${CURRDIR}


