#! /usr/bin/env bash
# jbegt_testpush
# last change: 20240823

# COLOR_SET="\e[1;94m"
# COLOR_SET="\e[1;34m"
COLOR_SET="\e[1;38;5;75m"
COLOR_RESET="\e[0m"
HST="jbe"
JDEST=${HOME}/majstaf/${HST}git/
JSTTS=${TMP}/${HST}git_status
JRPRT=${TMP}/${HST}git_report
> ${JSTTS}
> ${JRPRT}

CURRDIR=$PWD
cd ${JDEST}

echo "========================================"
echo "[INFO] running jbegt_testpush ..."
echo "========================================"
for DDD in $(find * -maxdepth 0 -type d); do
	printf "${COLOR_SET}"
	# echo "[INFO] git testpush in ${DDD} ... "
	echo "***    git testpush in ${DDD} ... ***"
	printf "${COLOR_RESET}"
	cd $DDD &>/dev/null && ~/.local/bin/ghgl_testpush_${HST} | tee -a ${JSTTS}
	grep -i 'pull' ${JSTTS} > /dev/null
	if [[ $? -eq 0 ]]; then
		echo "[REPORT] git testpush in: ${DDD} ... NEED TO PULL FROM REMOTE" >> ${JRPRT}
	fi
	# echo "---"
	> ${JSTTS}
	cd ..
done

printf "${COLOR_SET}"
if [ -s ${JRPRT} ]; then
	while read LINE; do
		echo "*** ${LINE} ***"
	done < ${JRPRT}
else
	echo "*** [REPORT] No action required ***"
fi
printf "${COLOR_RESET}"
rm ${JRPRT} ${JSTTS} 2>/dev/null

cd ${CURRDIR}
echo ""
