#! /usr/bin/env bash
# jvol_push_all
# last change: 20240821_jbe

export JBEVOLGITDIR="${HOME}/majstaf/jbegit/vlpprs_jbe"
export JBEVOLWORKDIR="${HOME}/majstaf/majvolpejpers"

git_jvol="/usr/bin/git --git-dir=${JBEVOLGITDIR} --work-tree=${JBEVOLWORKDIR}"

ghjvol="git@github.com:r-gregor/vlpprs_jbe.git"
gljvol="git@gitlab.com:r-gregor/vlpprs_jbe.git"

echo "[INFO] Push to ${ghjvol} ..."
${git_jvol} push ${ghjvol} main
echo "---"

echo "[INFO] Push to ${gljvol} ..."
${git_jvol} push ${gljvol} main
echo "---"

