#! /usr/bin/env bash
# jvol_push_all
# last update: 20240821_jbe

USR="mdb"

export JBEVOLGITDIR="${HOME}/majstaf/mdbgit/vlpprs_${USR}"
export JBEVOLWORKDIR="${HOME}/majstaf/majvolpejpers"

mdbg_vol="/usr/bin/git --git-dir=${JBEVOLGITDIR} --work-tree=${JBEVOLWORKDIR}"

echo "[INFO] Push to d_GITHUB ..."
${mdbg_vol} push git@github.com:r-gregor/vlpprs_${USR}.git main
echo "---"

echo "[INFO] Push to d_GITLAB ..."
${mdbg_vol} push git@gitlab.com:r-gregor/vlpprs_${USR}.git main
echo "---"

