#! /usr/bin/env bash
# jvol_testpush_all
# last update: 20240823

HST="jbe"

export VOLGITDIR="${HOME}/majstaf/${HST}git/vlpprs_${HST}"
export VOLWORKDIR="${HOME}/majstaf/majvolpejpers"

jbeg_vol="/usr/bin/git --git-dir=${VOLGITDIR} --work-tree=${VOLWORKDIR}"

echo "[INFO] Testpush to d_GITHUB ..."
${jbeg_vol} push --dry-run git@github.com:r-gregor/vlpprs_${HST}.git main
echo "---"

echo "[INFO] Testpush to d_GITLAB ..."
${jbeg_vol} push --dry-run git@gitlab.com:r-gregor/vlpprs_${HST}.git main
echo "---"

