#! /usr/bin/env bash
# testing_ghglstatus_jbe
# last update: 20240228_jbe


for DDD in $(ls -1 ~/majstaf/coding2/testing/); do
	echo "[INFO] Testing git status on ${DDD} ..."
	cd $DDD
	/usr/bin/git status
	cd ${HOME}
	echo -e "---\n"
done

